// <auto-generated />
namespace AppointmentsDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProCo_Property_Updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProCo_Property_Updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131920065_ProCo_Property_Updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
