// <auto-generated />
namespace AppointmentsDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocationGroupName_Mandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationGroupName_Mandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "201703212159296_LocationGroupName_Mandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
